name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build py3 wheels on ubuntu-22.04
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.3
      - name: Build wheels
        run: ./samba/dc.sh ./build_and_test_wheels.sh
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  build_wheels_py27:
    name: Build py27 wheel on ubuntu-22.04
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Build wheels
        run: ./samba/dc.sh ./build_and_test_wheels27.sh
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
